- hosts: localhost
  vars_files:
    - vars/external_vars.yml

  tasks:
  - bluecat:
      username: "{{ username }}"
      password: "{{ password }}"
      protocol: "{{ protocol }}"
      domain: "{{ domain }}"
      version: "{{ version }}"
      resource: configurations 
      action: post
      json_data:
        name: "{{ name }}"
    register: result

  - debug:
      var: result
