- hosts: localhost
  vars_files:
    - /vars/external_vars.yml
  tasks:
  - bluecat:
      username: "{{ username }}"
      password: "{{ password }}"
      protocol: "{{ protocol }}"
      domain: "{{ domain }}"
      version: "{{ version }}"
      resource: configurations 
      action: getall
    register: result

  - debug:
      var: result
