- hosts: localhost
  vars_files:
    - external_vars.yml
  tasks:
  - bluecat:
      username: "{{ username }}"
      password: "{{ password }}"
      protocol: "{{ protocol }}"
      domain: "{{ domain }}"
      version: "{{ version }}"
      resource: ipv4_network
      action: get
      resource_path:
        - block: "{{ block }}"
    register: result

  - debug:
      var: result
