- hosts: localhost
  vars_files:
    - external_vars.yml

  tasks:
  - bluecat:
      username: "{{ username }}"
      password: "{{ password }}"
      protocol: "{{ protocol }}"
      domain: "{{ domain }}"
      version: "{{ version }}"
      resource: host_record
      action: get
      resource_path:
        - absolute_name: "{{ absolute_name }}"
    register: result

  - debug:
      var: result
